blog/urls.py
from django.urls import path
from.import views

app_name = 'blog'

urlpatterns = [
    
    path('',views.index, name='home'),
    path('blog/',views.blog, name='blog'),
    path('category_blog/<slug>/',views.category_blogs, name='category_blogs'),
    path('tag_blog/<slug>/',views.tags_blogs, name='tags_blogs'),
    path('blog_details/<slug>/',views.blog_details, name='blog_details'),
    path('add_reply/<int:blog_id>/<int:comment_id>/',views.add_reply, name='add_reply'),
    path('like_blog/<int:pk>/',views.like_blog, name='like_blog' ),
    path('serch_blog/',views.search_blogs, name='search_blogs' ),
    path('my_blog/',views.my_blogs, name='my_blogs' ),
    path('add_blog/',views.add_blogs, name='add_blogs'),
    path('update_blog/<str:slug>/',views.update_blog, name='update_blog'),
]

testproject/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('',include('blog.urls',namespace='blog')),
    path ('',include('user_profile.urls',namespace='user_profile')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path
from . import views


app_name = 'user_profile'

urlpatterns = [
   
    path('login/',views.login_user,name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('registration/',views.register_user,name='register_user'),
    path('profile/',views.profile,name='profile'),
    path('profile_picture/',views.change_profile_picture,name='profile_picture'),
    path('user_information/<str:username>/',views.user_information,name='user_information'),
    path('follow_or_unfollow/<int:user_id>/',views.follow_or_unfollow_user,name='follow_or_unfollow_user'),
    path('notification/',views.user_notifications,name='user_notification'),
    path('mute_or_unmute_user/<int:user_id>/',views.mute_or_unmute_user,name='mute_or_unmute_user'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from user_profile.models import User
from django.utils.text import slugify
from.slugs import genaret_unique_slug
from ckeditor.fields import RichTextField


# Create your models here.


class Category(models.Model):
    title=models.CharField(max_length=150, unique=True)
    slug=models.SlugField(null=True, blank=True)
    created_date=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:category_blogs", args={
             self.slug
             })
    
    def save(self, *args, **kwargs):
        self.slug=slugify(self.title)
        super().save (*args, **kwargs)



class Tags(models.Model):
    title=models.CharField(max_length=150)
    slug=models.SlugField(null=True, blank=True)
    created_date=models.DateTimeField(auto_now_add=True)
    
    
    
    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        self.slug=slugify(self.title)
        super().save (*args, **kwargs)

    def get_tags_absolute_url(self):
        return reverse("blog:tags_blogs", args={
             self.slug
             })


class Blog (models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_blogs')
    category=models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_blogs')
    tags=models.ManyToManyField(Tags, related_name='tags', blank=True)
    likes=models.ManyToManyField(User, related_name='user_likes', blank=True)
    title=models.CharField(max_length=250)
    
    slug=models.SlugField(null=True, blank=True)
    banner=models.ImageField(upload_to='banner-images/')
    description=RichTextField()
    created_date=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        updating=self.pk is not None
        if updating:
            self.slug=genaret_unique_slug(self, self.title, update=True)
            super().save (*args, **kwargs)
        else:           
            self.slug=genaret_unique_slug(self, self.title)
            super().save (*args, **kwargs)


    def get_absolute_url(self):
        return reverse("blog:blog_details", kwargs={
            "slug": self.slug
            })


class Comment(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    blog=models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    text=models.TextField()
    created_date=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.text
    
    
    
class Reply(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_replies')
    comment=models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='comment_replies')
    text=models.TextField()
    created_date=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.text

notification/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from user_profile.models import User
# Create your models here.

class Notification(models.Model):
    NOTIFICATION_TYPE=('Blog','Like','Follow')
    content_type=models.ForeignKey(ContentType,on_delete=models.CASCADE)
    object_id=models.BigIntegerField()
    content_object=GenericForeignKey('content_type', 'object_id')
    user=models.ForeignKey(User, related_name='user_notifications', on_delete=models.CASCADE)
    text =models.CharField(max_length=150)
    is_seen=models.BooleanField(default=False)
    notification_type=models.CharField(max_length=20, choices=list(zip(NOTIFICATION_TYPE, NOTIFICATION_TYPE)))
    created_date=models.DateTimeField(auto_now_add=True)


    def __str__(self) -> str:
        return self.text

blog/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
from.models import  Blog
from ckeditor.fields import RichTextField


class TextForm(forms.Form):
    text=forms.CharField(widget=forms.Textarea, required=True)


class AddBlogForm(forms.ModelForm):
    description = RichTextField()
    class Meta:
        model=Blog
        fields=(
            'title',
            'category',
            'banner',
            'description',
        )

blog/views.py
from django.utils.text import slugify
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.http import JsonResponse

from user_profile.models import User
from.models import Category, Tags, Blog, Comment, Reply
from.forms import TextForm, AddBlogForm
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.


def index (request):
    blogs=Blog.objects.order_by('-created_date')
    tags=Tags.objects.order_by('-created_date')
    context={
        'blogs':blogs,
        'tags':tags,
    }
    return render(request,'index.html',context)

def blog (request):
    blogs=Blog.objects.order_by('-created_date')
    tags=Tags.objects.order_by('-created_date')
    
    paginator=Paginator(blogs,4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context={
        'blogs':blogs,
        'tags':tags,
        'page_obj':page_obj,
    }
    
    return render(request,'blog.html',context)

def category_blogs(request, slug):
    category=get_object_or_404(Category, slug=slug)
    recent_post=Blog.objects.order_by('-created_date')[:4]
    blogs=category.category_blogs.all()
    tags=Tags.objects.order_by('-created_date')[:4]
    paginator=Paginator(blogs,2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context={
        'blogs':blogs,
        'tags':tags,
        'page_obj':page_obj,
        'recent_post':recent_post,
    }
    return render(request,'category_blogs.html',context)


def tags_blogs(request, slug):
    tags=get_object_or_404(Tags, slug=slug)
    recent_post=Blog.objects.order_by('-created_date')[:4]
    blogs=tags.tags.all()
    tags=Tags.objects.order_by('-created_date')[:4]
    paginator=Paginator(blogs,2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context={
        'blogs':blogs,
        'tags':tags,
        'page_obj':page_obj,
        'recent_post':recent_post,
    }
    return render(request,'tags_blog.html',context)

def blog_details(request, slug):
    form=TextForm()
    blog=get_object_or_404(Blog, slug=slug)
    recent_post=Blog.objects.order_by('-created_date')[:4]
    tags=Tags.objects.order_by('-created_date')[:4]
    category=Category.objects.get(id=blog.category.id)
    related_blogs=category.category_blogs.all()
    liked_by=request.user in blog.likes.all()
    if request.method == 'POST' and request.user.is_authenticated:
        form=TextForm(request.POST)
        if form.is_valid():
            Comment.objects.create(
                user=request.user,
                blog=blog,   
                text=form.cleaned_data.get('text')
            )
            messages.success(request, 'Your comment submitted.')
            #return redirect('blog_details', slug=blog.slug)
            return HttpResponseRedirect(request.path_info)
    context={
        'blog':blog,
        'recent_post':recent_post,
        'tags':tags,
        'related_blogs':related_blogs,
        'form':form,
        'liked_by':liked_by
    }

    return render(request,'blog_details.html',context)

@login_required(login_url='user_profile:login')
def add_reply(request, blog_id, comment_id):
    blog=get_object_or_404(Blog, id=blog_id)  
    if request.method == 'POST':
        form=TextForm(request.POST)
        if form.is_valid():
            comment = get_object_or_404(Comment, id=comment_id)
            Reply.objects.create(
                user=request.user,
                comment=comment,  
                text=form.cleaned_data.get('text')
            )
            messages.success(request, 'Your comment submitted.')
            return redirect('blog:blog_details', slug=blog.slug)
    return redirect('blog:blog_details', slug=blog.slug)


@login_required(login_url='user_profile:login')
def like_blog(request, pk):
    context={}
    blog=get_object_or_404(Blog, pk=pk)
    if request.user in blog.likes.all():
        blog.likes.remove(request.user)
        context['liked'] =False
        context['like_count']= blog.likes.all().count()

    else:
        blog.likes.add(request.user)
        context['liked'] =True
        context['like_count']= blog.likes.all().count()

    return JsonResponse(context, safe=False)

def search_blogs(request):
    search_key =request.GET.get('search', None)
    tags=Tags.objects.order_by('-created_date')
    
    if search_key:
        blogs=Blog.objects.filter(
            Q(title__icontains=search_key) |
            Q(category__title__icontains=search_key) |
            Q(user__username__icontains=search_key) |
            Q(tags__title__icontains=search_key) |
            Q(description__icontains=search_key) 

        ).distinct()

        paginator=Paginator(blogs,4)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context={
            'blogs':blogs,
            'page_obj':page_obj,
            'tags':tags,
            'search_key':search_key,
        }
        return render(request,'search.html',context)

    else:
        #return redirect('blog:home')

        blogs=Blog.objects.order_by('-created_date')
        tags=Tags.objects.order_by('-created_date')

        paginator=Paginator(blogs,2)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context={
            'blogs':blogs,
            'page_obj':page_obj,
            'tags':tags,
        }
        return render(request,'search.html',context)
            

            
@login_required(login_url='user_profile:login')      
def my_blogs(request):
    queryset=request.user.user_blogs.all()
    paginator=Paginator(queryset,3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    delete=request.GET.get('delete', None)

    if delete:

        blog=get_object_or_404(Blog, pk=delete)

        if request.user.pk != blog.user.pk:
            return redirect('blog:home')
        blog.delete()
        messages.success(request, 'Your blog has been deleted')
        return redirect('blog:my_blogs')
    context={
        'queryset':queryset,
        'page_obj':page_obj,

    }
    return render(request,'my_blogs.html',context)  
    

@login_required(login_url='user_profile:login')      
def add_blogs(request):
    form = AddBlogForm()
    if request.method == 'POST':
        form = AddBlogForm(request.POST, request.FILES)
        if form.is_valid():
            tags=request.POST['tags'].split(',')
            user=get_object_or_404(User, pk=request.user.pk)
            category=get_object_or_404(Category, pk=request.POST['category'])
            blog=form.save(commit=False)
            blog.user=user
            blog.category=category
            blog.save()
            for tag in tags:
                tag_input = Tags.objects.filter(
                    title__iexact=tag.strip(),
                    slug=slugify(tag.strip())
                )
                if tag_input.exists():
                    t=tag_input.first()
                    blog.tags.add(t)
                else:
                    if tag != '':
                        new_tag=Tags.objects.create(
                        title=tag.strip(),
                        slug=slugify(tag.strip())
                        )
                        blog.tags.add(new_tag)
                    
            messages.success(request,'Blog Added successfully')
            return redirect('blog:blog_details', slug=blog.slug)

        else:
            print(form.errors)

    context={
        'form':form,
    }

    return render(request,'addblog.html',context) 

@login_required(login_url='user_profile:login')      
def update_blog(request, slug):
    form = AddBlogForm()
    blog=get_object_or_404(Blog, slug=slug)
    form = AddBlogForm(instance=blog)

    if request.method == 'POST':
        form = AddBlogForm(request.POST, request.FILES, instance=blog)

        if form.is_valid():

            if request.user.pk != blog.user.pk:
                return redirect ('blog:home')

            tags=request.POST['tags'].split(',')
            user=get_object_or_404(User, pk=request.user.pk)
            category=get_object_or_404(Category, pk=request.POST['category'])
            blog=form.save(commit=False)
            blog.user=user
            blog.category=category
            blog.save()
            for tag in tags:
                tag_input = Tags.objects.filter(
                    title__iexact=tag.strip(),
                    slug=slugify(tag.strip())
                )
                if tag_input.exists():
                    t=tag_input.first()
                    blog.tags.add(t)
                else:
                    if tag != '':
                        new_tag=Tags.objects.create(
                        title=tag.strip(),
                        slug=slugify(tag.strip())
                        )
                        blog.tags.add(new_tag)
                    
            messages.success(request,'Blog updated successfully')
            return redirect('blog:blog_details', slug=blog.slug)

        else:
            print(form.errors)

    context={
        'form':form,
        'blog':blog,
    }

    return render(request,'update_blog.html',context) 

notification/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
    <title>{% block title %}   {% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'blog/assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'blog/assets/css/templatemo-stand-blog.css' %}">
    <link rel="stylesheet" href="{% static 'blog/assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'blog/assets/css/main.css' %}">
<!--

TemplateMo 551 Stand Blog

https://templatemo.com/tm-551-stand-blog

-->
  </head>

  <body>

  


    {% include "header.html" %}


    
    {% block maincontent %}
        
    {% endblock maincontent %}

    {% include "footer.html" %}
    {% include "script.html" %}


        

</body>
</html>

templates/blog_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Blogs_Details  {% endblock title %}

{% block maincontent %}


  <section class="blog-posts grid-system">
    
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="all-blog-posts">
            <div class="row">
              <div class="col-lg-12">
          {% if messages %}	
		      {% for massage in messages %}
  	      <div class="alert alert-{{massage.tags }} alert-dismissible fade show" role="alert">
			      <strong>{{ massage }} </strong> 
			    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		      </div>
		      {% endfor %}
		      {% endif %}
                <div class="blog-post">
                  <div class="blog-thumb">
                    <img src="{{ blog.banner.url }}" alt="">
                  </div>
                  <div class="down-content">
                    <span>{{ blog.category }}</span>
                    <a href="{% url 'blog:blog_details' blog.slug %}"><h4>{{ blog.title }}</h4></a>
                    <ul class="post-info">
                        <li><a href="{% url 'user_profile:user_information' blog.user.username %}">{{ blog.user.username }}</a></li>
                        <li><a href="javascript:void(0);">{{ blog.created_date | date }}</a></li>
                        <li><a href="javascript:void(0);">{{ blog.blog_comment.all.count }} Comments </a></li>
                      </ul>
                      <p>{{ blog.description | truncatewords:20 | safe }} </p>
                    
                    
                    <div class="post-options">
                      <div class="row">
                        <div class="col-6">
                          <ul class="post-tags">
                            <li><i class="fa fa-tags"></i></li>
                            {% if blog.tags.all.count > 0 %}
                               
                              {% for tag in blog.tags.all %}
                          
                              <li><a href="#">{{ tag.title }}</a></li>
                              {% endfor %}
                              {% else  %}
                                None
                              {% endif %}
                          </ul>
                        </div>
                        {% if request.user.is_authenticated %} 
                        
                        <div class="col-6">
                          <ul class="post-share">
                            <li id="like-count">{{ blog.likes.count }}</li>
                            {% if liked_by %}
                            <li class="pl-3 pr-3"><a href="javascript:void(0);"><i id="like-icon" data-blog="{{ blog.id }}" class="fa fa-heart"></i></a></li>
                            {% else %}
                            <li class="pl-3 pr-3"><a href="javascript:void(0);"><i id="like-icon" data-blog="{{ blog.id }}" class="fa fa-heart empty-heart"></i></a></li>
                            {% endif %}
                             
                            <li><i class="fa fa-share-alt"></i></li>
                            <li><a href="#">Facebook</a>,</li>
                            <li><a href="#"> Twitter</a></li>
                          </ul>
                        </div>
                        {% else %}
                        <div class="col-6">
                          <ul class="post-share">
                            <li id="like-count">{{ blog.likes.count }}</li>
                            {% if liked_by %}
                            <li class="pl-3 pr-3"><a href="{% url 'user_profile:login' %}"><i class="fa fa-heart"></i></a></li>
                            {% else %}
                            <li class="pl-3 pr-3"><a href="{% url 'user_profile:login' %}"><i class="fa fa-heart empty-heart"></i></a></li>
                            {% endif %}
                            <li><i class="fa fa-share-alt"></i></li>
                            <li><a href="#">Facebook</a>,</li>
                            <li><a href="#"> Twitter</a></li>
                          </ul>
                        </div>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="sidebar-item comments">
                  <div class="sidebar-heading">
                    <h2>{{ blog.blog_comment.count }} Comments</h2>
                  </div>
                  <div class="content">
                    <ul class="d-flex flex-column">
                        {% for comment in blog.blog_comment.all %}
                            
                        
                      <li>
                        <div class="author-thumb">
                          <img src="{{ comment.user.get_profile_piture }}" alt="images">
                        </div>
                        <div class="right-content">
                          <h4>{{ comment.user.username }}<span>{{ comment.created_date | date }}</span></h4>
                         <p>{{ comment.text }}</p>

                         <form class="submit-reply my-2" id="comment" action="{% url 'blog:add_reply' blog.id comment.id %}" method="POST">
                          {% csrf_token %}
                        <div class="row">
                          
                          
                          <div class="col-lg-12">
                            <fieldset>
                              <textarea name="text" rows="2" cols="50" id="message" placeholder="Type Your Reply comment" required=""></textarea>
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                                
                              {% if request.user.is_authenticated %}           
                              <button type="submit" id="form-submit" class="main-button reply-button">Reply</button>
                              {% else %}
                              <a href="{% url 'user_profile:login' %}"  id="form-submit" class="main-button reply-button"> Login to Reply </a>
                              {% endif %}
                            </fieldset>
                          </div>
                        </div>
                      </form>
                        </div>
                      </li>
                      {% for reply in comment.comment_replies.all %}
                        
                      
                      <li class="replied">
                        <div class="author-thumb">
                          <img src="{{ reply.user.get_profile_piture }}" alt="">
                        </div>
                        <div class="right-content">
                          <h4>{{ reply.user.username }}<span>{{ reply.created_date | date }}</span></h4>
                          <p>{{ reply.text }}</p>
                        </div>
                      </li>
                      {% endfor %}
                      {% endfor %}
                      
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="sidebar-item submit-comment">
                  <div class="sidebar-heading">
                    <h2>Your comment</h2>
                  </div>
                  <div class="content">
                    <form id="comment" action="{% url 'blog:blog_details' blog.slug %}" method="POST">
                        {% csrf_token %}
                      <div class="row">
                        
                        
                        <div class="col-lg-12">
                          <fieldset>
                            <textarea name="text" rows="6" id="message" placeholder="Type your comment" required=""></textarea>
                          </fieldset>
                        </div>
                        <div class="col-lg-12">
                          <fieldset>
                              
                            {% if request.user.is_authenticated %}           
                            <button type="submit" id="form-submit" class="main-button">Submit</button>
                            {% else %}
                          <a  href="{% url 'user_profile:login' %}" id="form-submit" class="main-button btn btn-warning "> Login to comment </a>
                            {% endif %}
                          </fieldset>
                        </div>
                      </div>
                    </form>



                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="sidebar">
            <div class="row">
              <div class="col-lg-12">
                <div class="sidebar-item recent-posts sidebar-item search">
                  <div class="sidebar-heading">
                    <h2>Releted Posts</h2>
                  </div>
                  <div class="content">
                    <ul>

                      {% for blog in related_blogs %}
                      <li><a href="{% url 'blog:blog_details' blog.slug %}">
                        <h5>{{ blog.title }}</h5>
                        <span>{{ blog.created_date | date }}</span>
                      </a></li>
                     {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="sidebar-item categories">
                  <div class="sidebar-heading">
                    <h2>Categories</h2>
                  </div>
                  <div class="content">
                    <ul>
                      {% for category in categories %}
                          
                      
                      <li><a href="{{ category.get_absolute_url }}">{{ category.title }}</a></li>
                      {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="sidebar-item tags">
                  <div class="sidebar-heading">
                    <h2>Tag Clouds</h2>
                  </div>
                  <div class="content">
                    
                    <ul>
                      {% for tag in tags %}
                          
                      
                      <li><a href="{{ tag.get_tags_absolute_url }}">{{ tag.title }}</a></li>
                      {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>










{% endblock maincontent %}

templates/header.html
{% load static %}
  
   <!-- Header -->
    <header class="">
        <nav class="navbar navbar-expand-lg">
          <div class="container">
            <a class="navbar-brand" href=""><h2>Stand Blog<em>.</em></h2></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="/">Home
                    <span class="sr-only">(current)</span>
                  </a>
                </li> 
                
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'blog:blog' %}">Blogs</a>
                </li>
               
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true">
                    Category
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    
                  {% for category in categories %}
                        
                    
                    <li><a class="dropdown-item" href="{% url 'blog:category_blogs' category.slug %}">{{ category.title }}</a></li>
                    {% endfor %}
                  </ul>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true">
                    {{ request.user.username }}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
               
                    <li><a class="dropdown-item" href="{% url 'user_profile:profile' %}">My Profile </a></li>
                    <li><a class="dropdown-item" href="{% url 'user_profile:user_notification' %}">
                      {% if unseen > 0 %}
                      Notification ({{ unseen }})
                      {% else %}
                      Notification 
                      {% endif %}
                    </a></li>
                    <li><a class="dropdown-item" href="{% url 'user_profile:logout' %}">Logout </a></li>

                  </ul>
                </li>
                {% else %}

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user_profile:login' %}">login</a>
                </li>
                {% endif %}
                <form class="form-inline d-flex flex-nowrap my-2 ml-auto search-form" action="{% url 'blog:search_blogs' %}" method="GET">
                  <input class="form-control px-5" name="search" type="text" placeholder="Search Blogs">
                  <button class="btn btn-primary ml-1">Search</button>
                </form>

              </ul>
            </div>
          </div>
        </nav>
      </header>